---
title: "Make a Plink file"
output: html_notebook
---

https://github.com/bulik/ldsc

```{r install_libraries}

source("https://bioconductor.org/biocLite.R")
biocLite("snpStats") # https://www.bioconductor.org/packages//2.10/bioc/html/snpStats.html

library(BiocManager)
library(biomaRt)
library(snpEnrichment) # https://rdrr.io/cran/snpEnrichment/man/writeLD.html

```

```{r specify_data}

# http://webcache.googleusercontent.com/search?q=cache:http://zzz.bwh.harvard.edu/plink/dosage.shtml#format

chr1_cis <- franke_cis_data[which(GeneChr==1),]
chr1_cis_split <- split(chr1_cis, chr1_cis$GeneSymbol)
ACBD6 <- chr1_cis_split[[11]] # ACBD6
```

```{r }

fwrite(data.table(ACBD6$SNP), "/Users/kathryntsai/OneDrive\ -\ Villanova\ University/College/2018-2019/Summer\ 2019/TFs_eQTLs_Research/RProjects/Project2/finemapping/acbd6_snps.txt", row.names=F, col.names=F)

```


```{r make_map_1_gene_locus}

map_file <- data.table(ACBD6$SNPChr, ACBD6$SNP, 0, ACBD6$SNPPos)
fwrite(map_file, "/Users/kathryntsai/OneDrive\ -\ Villanova\ University/College/2018-2019/Summer\ 2019/TFs_eQTLs_Research/RProjects/Project2/finemapping/acbd6.map", sep="\t", col.names = F, row.names=F)
```


https://web.archive.org/web/20190528204434/http://zzz.bwh.harvard.edu/plink/data.shtml
Have to make up information for summary stats:
     Family ID
     Individual ID
     Paternal ID
     Maternal ID
     Sex (1=male; 2=female; other=unknown)
     Phenotype
http://cubre.covenantuniversity.edu.ng/wp-content/uploads/2014/07/H3ABionet_2014_GWAS_2_Plink_Data_Format.pdf

```{r make_ped_1_gene_locus}

ACBD6_table <- data.table(ACBD6$SNP, ACBD6$OtherAllele, ACBD6$AssessedAllele)
colnames(ACBD6_table) <- c("SNP", "Ref", "Alt")
#ACBD6_table_melted <- melt(ACBD6_table, id.vars="SNP") 
#ACBD6_table_melted_alleles <- ACBD6_table_melted[order(ACBD6_table_melted$SNP), "value"]

#cbind(ACBD6_table[seq(1, nrow(ACBD6_table), by=2), -1], ACBD6_table[seq(2, nrow(ACBD6_table), by=2), -1])

acbd6_alleles <- strsplit(paste0(paste0(ACBD6_table$Ref, ACBD6_table$Alt), sep="", collapse=""), split="")

ped_file <- data.table("chr1", "acbd6", 0, 0, 3, -9, t(acbd6_alleles[[1]]))
fwrite(ped_file, "/Users/kathryntsai/OneDrive\ -\ Villanova\ University/College/2018-2019/Summer\ 2019/TFs_eQTLs_Research/RProjects/Project2/finemapping/acbd6.ped", sep="\t", col.names = F, row.names=F)
```

```{r plink_test, include=F}

# in plink_mac_20190907 folder
# create test.ped, test.map --> create toy_analysis.frq, toy_analysis.log
system("/Users/kathryntsai/plink-1.07-mac-intel/plink --file test --freq --out toy_analysis --noweb") # getting started
# test.fam, test.bim, test.bed, test.log
system("/Users/kathryntsai/plink-1.07-mac-intel/plink --file test --maf 0.05 --make-bed --out test") # https://www.cog-genomics.org/plink/1.9/data#make_bed
# plink.ld, plink.log
system("/Users/kathryntsai/plink-1.07-mac-intel/plink --file test --r")
```

https://www.cog-genomics.org/plink/1.9/ld 
https://www.cog-genomics.org/plink/1.9/data#make_bed
https://web.archive.org/web/20181008145054/http://zzz.bwh.harvard.edu/plink/ld.shtml

```{r run_plink_1_gene_locus}

# in /Users/kathryntsai/OneDrive - Villanova University/College/2018-2019/Summer 2019/TFs_eQTLs_Research/RProjects/Project2/finemapping
system("/Users/kathryntsai/plink-1.07-mac-intel/plink --file acbd6 --allow-no-sex --make-bed --out acbd6") 
#system("/Users/kathryntsai/plink-1.07-mac-intel/plink --file acbd6 --r") # pariwise snps

#/Users/kathryntsai/plink-1.07-mac-intel/plink --r2 --bfile acbd6 --extract samplesnp.txt --ld-window-r2 0.8 --out acbd6_ld

/Users/kathryntsai/plink-1.07-mac-intel/plink --r2 --bfile acbd6 --extract acbd6_snps.txt --ld-window-r2 0.8 --out acbd6_ld


```

