---
title: "R Notebook"
output: html_notebook
---

```{r install_libraries}

source("https://bioconductor.org/biocLite.R")
biocLite("snpStats") # https://www.bioconductor.org/packages//2.10/bioc/html/snpStats.html

library(BiocManager)
library(biomaRt)
library(snpEnrichment) # https://rdrr.io/cran/snpEnrichment/man/writeLD.html

```


```{r make_plink_files}

chr1_cis <- franke_cis_data[which(GeneChr==1),]
chr1_cis_split <- split(chr1_cis, chr1_cis$GeneSymbol)
chr1_cis_useful <- chr1_cis_split[[10]] # ACBD3

fwrite(chr1_cis_useful$SNP, "SNPs_for_plink_ACBD3.txt", sep="\t")

fwrite(data.table(chr1_cis_useful$SNP, chr1_cis_useful$Zscore), "Zscore_file_ACBD3.txt", sep="\t")

```

```{r write_plinke_files_from_computer}

snpInfoDir <- system.file("extdata/snpInfo",
                          package = "snpEnrichment")

SNPs_Pvalues <- data.table(chr1_cis_useful$SNP, chr1_cis_useful$Pvalue)
colnames(SNPs_Pvalues) <- c("SNP", "PVALUE")
fwrite(SNPs_Pvalues, "/Users/kathryntsai/OneDrive - Villanova University/College/2018-2019/Summer 2019/TFs_eQTLs_Research/RProjects/Project2/finemapping/signalFile.txt", sep="\t", quote=F)

signalFile <- "/Users/kathryntsai/OneDrive - Villanova University/College/2018-2019/Summer 2019/TFs_eQTLs_Research/RProjects/Project2/finemapping/signalFile.txt"

ldDir <- "/Users/kathryntsai/OneDrive - Villanova University/College/2018-2019/Summer 2019/TFs_eQTLs_Research/RProjects/Project2/finemapping"

writeLD(pattern = "Chrom", snpInfoDir, signalFile, 
        ldDir, ldThresh = 0.8, depth = 1000)

```

